title: <p align="center"> Francis Rinehart </p>

logo: "/images/picture.png?raw=true"

description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/frinehart/">LinkedIn</a> |
  <a href="https://github.com/frinehart">GitHub</a>
  <a href="https://github.com/frinehart">GitHub</a>
  <a href="https://github.com/frinehart">GitHub</a>
  </p>
  
  <p align="justify">
  I graduated with a B.S. in Computer Science with a minor in Mathematics in 2021 at Southern New Hampshire University. 
  <br><br>
  I am currently a target worker at OSI and a research assistant at Aiscite Institute. I have a background in Python and SQL.
  </p>

theme: jekyll-theme-minimal
